config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  resources :posts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DrillApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      DRILL APP
    </header>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="content">
  <div class="content-message">
    <%= post.text %>
  </div>
  <div class="content-date">
    <%= post.created_at %>
  </div>
</div>

app/views/posts/index.html.erb
<h1>トップページ</h1>
<div class="wrapper">
  <div class="top-left">
    <%= link_to "投稿ページ",  new_post_path, class: "top-btn"%>
  </div>
  <div class="contents">
    <% @posts.each do |post|%>
      <%= render partial: "post", locals: { post: post } %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>新規投稿ページ</h1>
<%= form_with model: @post, local: true do |form| %>
  <%= form.text_field :text %>
  <%= form.submit '投稿する' %>
<% end %>